server:
  port: 8080



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.recommendation.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
spring:
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/recommendation?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      username: root
      password: 278956
  kafka:
    bootstrap-servers: hadoop101:9092,hadoop102:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer